CREATE TABLE IF NOT EXISTS profile_has_post (
	id BIGSERIAL PRIMARY KEY,
	profile_id BIGINT NOT NULL,
	post_id BIGINT NOT NULL,
	FOREIGN KEY(profile_id) 
		REFERENCES profile(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(post_id)
		REFERENCES post(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);