// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: city.sql

package db

import (
	"context"
	"database/sql"
)

const getCities = `-- name: GetCities :many
SELECT id, name
FROM city
WHERE name LIKE '%' || $1 || '%'
LIMIT 20
`

func (q *Queries) GetCities(ctx context.Context, name sql.NullString) ([]City, error) {
	rows, err := q.db.QueryContext(ctx, getCities, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
