// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: ingredient.sql

package db

import (
	"context"
	"database/sql"
)

const getIngredientId = `-- name: GetIngredientId :one
SELECT id
FROM ingredient
WHERE name = $1
`

func (q *Queries) GetIngredientId(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getIngredientId, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getSimilarIngredient = `-- name: GetSimilarIngredient :many
SELECT name
FROM ingredient
WHERE name LIKE $1 || '%'
ORDER BY usage DESC
LIMIT 10
`

func (q *Queries) GetSimilarIngredient(ctx context.Context, name sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSimilarIngredient, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIngredient = `-- name: InsertIngredient :one
INSERT INTO ingredient (name)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertIngredient(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertIngredient, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
