// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: post_has_ingredient.sql

package db

import (
	"context"
	"database/sql"
)

const getPostIngredient = `-- name: GetPostIngredient :many
SELECT i.name, p.amount
FROM post_has_ingredient p JOIN ingredient i ON p.ingredient_id = i.id
WHERE p.post_id = $1
`

type GetPostIngredientRow struct {
	Name   string
	Amount sql.NullString
}

func (q *Queries) GetPostIngredient(ctx context.Context, postID int64) ([]GetPostIngredientRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostIngredient, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostIngredientRow
	for rows.Next() {
		var i GetPostIngredientRow
		if err := rows.Scan(&i.Name, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPostHasIngredient = `-- name: InsertPostHasIngredient :exec
INSERT INTO post_has_ingredient (post_id, ingredient_id, amount)
VALUES ($1, $2, $3)
`

type InsertPostHasIngredientParams struct {
	PostID       int64
	IngredientID int32
	Amount       sql.NullString
}

func (q *Queries) InsertPostHasIngredient(ctx context.Context, arg InsertPostHasIngredientParams) error {
	_, err := q.db.ExecContext(ctx, insertPostHasIngredient, arg.PostID, arg.IngredientID, arg.Amount)
	return err
}
