// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: post.sql

package db

import (
	"context"
)

const getPost = `-- name: GetPost :one
SELECT id, title, description, num_images
FROM post
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.NumImages,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :one
INSERT INTO post (title, description, num_images)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertPostParams struct {
	Title       string
	Description string
	NumImages   int16
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPost, arg.Title, arg.Description, arg.NumImages)
	var id int64
	err := row.Scan(&id)
	return id, err
}
