// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "media.proto" (package "KhanAPI", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MediaAPI } from "./media";
/**
 * @generated from protobuf service KhanAPI.MediaAPI
 */
export interface IMediaAPIClient {
}
/**
 * @generated from protobuf service KhanAPI.MediaAPI
 */
export class MediaAPIClient implements IMediaAPIClient, ServiceInfo {
    typeName = MediaAPI.typeName;
    methods = MediaAPI.methods;
    options = MediaAPI.options;
    constructor(private readonly _transport: RpcTransport) {
    }
}
