// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "media.proto" (package "KhanAPI", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service KhanAPI.MediaAPI
 */
export const MediaAPI = new ServiceType("KhanAPI.MediaAPI", []);
