// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "post.proto" (package "KhanAPI", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PostAPI } from "./post";
import type { SuggestIngredientResponse } from "./post";
import type { SuggestIngredientRequest } from "./post";
import type { Empty } from "./google/protobuf/empty";
import type { SetPostRequest } from "./post";
import type { GetPostResponse } from "./post";
import type { GetPostRequest } from "./post";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetProfilePostsResponse } from "./post";
import type { GetProfilePostsRequests } from "./post";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service KhanAPI.PostAPI
 */
export interface IPostAPIClient {
    /**
     * @generated from protobuf rpc: GetProfilePosts(KhanAPI.GetProfilePostsRequests) returns (KhanAPI.GetProfilePostsResponse);
     */
    getProfilePosts(input: GetProfilePostsRequests, options?: RpcOptions): UnaryCall<GetProfilePostsRequests, GetProfilePostsResponse>;
    /**
     * @generated from protobuf rpc: GetPost(KhanAPI.GetPostRequest) returns (KhanAPI.GetPostResponse);
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse>;
    /**
     * @generated from protobuf rpc: SetPost(KhanAPI.SetPostRequest) returns (google.protobuf.Empty);
     */
    setPost(input: SetPostRequest, options?: RpcOptions): UnaryCall<SetPostRequest, Empty>;
    /**
     * @generated from protobuf rpc: SuggestIngredient(KhanAPI.SuggestIngredientRequest) returns (KhanAPI.SuggestIngredientResponse);
     */
    suggestIngredient(input: SuggestIngredientRequest, options?: RpcOptions): UnaryCall<SuggestIngredientRequest, SuggestIngredientResponse>;
}
/**
 * @generated from protobuf service KhanAPI.PostAPI
 */
export class PostAPIClient implements IPostAPIClient, ServiceInfo {
    typeName = PostAPI.typeName;
    methods = PostAPI.methods;
    options = PostAPI.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetProfilePosts(KhanAPI.GetProfilePostsRequests) returns (KhanAPI.GetProfilePostsResponse);
     */
    getProfilePosts(input: GetProfilePostsRequests, options?: RpcOptions): UnaryCall<GetProfilePostsRequests, GetProfilePostsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfilePostsRequests, GetProfilePostsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPost(KhanAPI.GetPostRequest) returns (KhanAPI.GetPostResponse);
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostRequest, GetPostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetPost(KhanAPI.SetPostRequest) returns (google.protobuf.Empty);
     */
    setPost(input: SetPostRequest, options?: RpcOptions): UnaryCall<SetPostRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetPostRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SuggestIngredient(KhanAPI.SuggestIngredientRequest) returns (KhanAPI.SuggestIngredientResponse);
     */
    suggestIngredient(input: SuggestIngredientRequest, options?: RpcOptions): UnaryCall<SuggestIngredientRequest, SuggestIngredientResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SuggestIngredientRequest, SuggestIngredientResponse>("unary", this._transport, method, opt, input);
    }
}
