// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "post.proto" (package "KhanAPI", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PostAPI } from "./post";
import type { SearchFoodByIngredientResponse } from "./post";
import type { SearchFoodByIngredientRequest } from "./post";
import type { SearchFoodByNameResponse } from "./post";
import type { SearchFoodByNameRequest } from "./post";
import type { GetCategoriesResponse } from "./post";
import type { LikeCommentRequest } from "./post";
import type { GetRepliesResponse } from "./post";
import type { GetRepliesRequest } from "./post";
import type { SearchCategoriesResponse } from "./post";
import type { SearchCategoriesRequest } from "./post";
import type { GetCommentsResponse } from "./post";
import type { GetCommentsRequest } from "./post";
import type { AddReplyRequest } from "./post";
import type { AddCommentRequest } from "./post";
import type { DislikeRequest } from "./post";
import type { LikeRequest } from "./post";
import type { Empty } from "./google/protobuf/empty";
import type { AddImageForPostRequest } from "./post";
import type { SuggestIngredientResponse } from "./post";
import type { SuggestIngredientRequest } from "./post";
import type { SetPostResponse } from "./post";
import type { SetPostRequest } from "./post";
import type { GetPostResponse } from "./post";
import type { GetPostRequest } from "./post";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetProfilePostsResponse } from "./post";
import type { GetProfilePostsRequests } from "./post";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service KhanAPI.PostAPI
 */
export interface IPostAPIClient {
    /**
     * @generated from protobuf rpc: GetProfilePosts(KhanAPI.GetProfilePostsRequests) returns (KhanAPI.GetProfilePostsResponse);
     */
    getProfilePosts(input: GetProfilePostsRequests, options?: RpcOptions): UnaryCall<GetProfilePostsRequests, GetProfilePostsResponse>;
    /**
     * @generated from protobuf rpc: GetPost(KhanAPI.GetPostRequest) returns (KhanAPI.GetPostResponse);
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse>;
    /**
     * @generated from protobuf rpc: SetPost(KhanAPI.SetPostRequest) returns (KhanAPI.SetPostResponse);
     */
    setPost(input: SetPostRequest, options?: RpcOptions): UnaryCall<SetPostRequest, SetPostResponse>;
    /**
     * @generated from protobuf rpc: SuggestIngredient(KhanAPI.SuggestIngredientRequest) returns (KhanAPI.SuggestIngredientResponse);
     */
    suggestIngredient(input: SuggestIngredientRequest, options?: RpcOptions): UnaryCall<SuggestIngredientRequest, SuggestIngredientResponse>;
    /**
     * @generated from protobuf rpc: AddImageForPost(KhanAPI.AddImageForPostRequest) returns (google.protobuf.Empty);
     */
    addImageForPost(input: AddImageForPostRequest, options?: RpcOptions): UnaryCall<AddImageForPostRequest, Empty>;
    /**
     * @generated from protobuf rpc: Like(KhanAPI.LikeRequest) returns (google.protobuf.Empty);
     */
    like(input: LikeRequest, options?: RpcOptions): UnaryCall<LikeRequest, Empty>;
    /**
     * @generated from protobuf rpc: Dislike(KhanAPI.DislikeRequest) returns (google.protobuf.Empty);
     */
    dislike(input: DislikeRequest, options?: RpcOptions): UnaryCall<DislikeRequest, Empty>;
    /**
     * @generated from protobuf rpc: AddComment(KhanAPI.AddCommentRequest) returns (google.protobuf.Empty);
     */
    addComment(input: AddCommentRequest, options?: RpcOptions): UnaryCall<AddCommentRequest, Empty>;
    /**
     * @generated from protobuf rpc: AddReply(KhanAPI.AddReplyRequest) returns (google.protobuf.Empty);
     */
    addReply(input: AddReplyRequest, options?: RpcOptions): UnaryCall<AddReplyRequest, Empty>;
    /**
     * @generated from protobuf rpc: GetComments(KhanAPI.GetCommentsRequest) returns (KhanAPI.GetCommentsResponse);
     */
    getComments(input: GetCommentsRequest, options?: RpcOptions): UnaryCall<GetCommentsRequest, GetCommentsResponse>;
    /**
     * @generated from protobuf rpc: SearchCategories(KhanAPI.SearchCategoriesRequest) returns (KhanAPI.SearchCategoriesResponse);
     */
    searchCategories(input: SearchCategoriesRequest, options?: RpcOptions): UnaryCall<SearchCategoriesRequest, SearchCategoriesResponse>;
    /**
     * @generated from protobuf rpc: GetReplies(KhanAPI.GetRepliesRequest) returns (KhanAPI.GetRepliesResponse);
     */
    getReplies(input: GetRepliesRequest, options?: RpcOptions): UnaryCall<GetRepliesRequest, GetRepliesResponse>;
    /**
     * @generated from protobuf rpc: LikeComment(KhanAPI.LikeCommentRequest) returns (google.protobuf.Empty);
     */
    likeComment(input: LikeCommentRequest, options?: RpcOptions): UnaryCall<LikeCommentRequest, Empty>;
    /**
     * @generated from protobuf rpc: GetCategories(google.protobuf.Empty) returns (KhanAPI.GetCategoriesResponse);
     */
    getCategories(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetCategoriesResponse>;
    /**
     * @generated from protobuf rpc: SearchFoodByName(KhanAPI.SearchFoodByNameRequest) returns (KhanAPI.SearchFoodByNameResponse);
     */
    searchFoodByName(input: SearchFoodByNameRequest, options?: RpcOptions): UnaryCall<SearchFoodByNameRequest, SearchFoodByNameResponse>;
    /**
     * @generated from protobuf rpc: SearchFoodByIngredient(KhanAPI.SearchFoodByIngredientRequest) returns (KhanAPI.SearchFoodByIngredientResponse);
     */
    searchFoodByIngredient(input: SearchFoodByIngredientRequest, options?: RpcOptions): UnaryCall<SearchFoodByIngredientRequest, SearchFoodByIngredientResponse>;
}
/**
 * @generated from protobuf service KhanAPI.PostAPI
 */
export class PostAPIClient implements IPostAPIClient, ServiceInfo {
    typeName = PostAPI.typeName;
    methods = PostAPI.methods;
    options = PostAPI.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetProfilePosts(KhanAPI.GetProfilePostsRequests) returns (KhanAPI.GetProfilePostsResponse);
     */
    getProfilePosts(input: GetProfilePostsRequests, options?: RpcOptions): UnaryCall<GetProfilePostsRequests, GetProfilePostsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfilePostsRequests, GetProfilePostsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPost(KhanAPI.GetPostRequest) returns (KhanAPI.GetPostResponse);
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, GetPostResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostRequest, GetPostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetPost(KhanAPI.SetPostRequest) returns (KhanAPI.SetPostResponse);
     */
    setPost(input: SetPostRequest, options?: RpcOptions): UnaryCall<SetPostRequest, SetPostResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetPostRequest, SetPostResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SuggestIngredient(KhanAPI.SuggestIngredientRequest) returns (KhanAPI.SuggestIngredientResponse);
     */
    suggestIngredient(input: SuggestIngredientRequest, options?: RpcOptions): UnaryCall<SuggestIngredientRequest, SuggestIngredientResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SuggestIngredientRequest, SuggestIngredientResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddImageForPost(KhanAPI.AddImageForPostRequest) returns (google.protobuf.Empty);
     */
    addImageForPost(input: AddImageForPostRequest, options?: RpcOptions): UnaryCall<AddImageForPostRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddImageForPostRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Like(KhanAPI.LikeRequest) returns (google.protobuf.Empty);
     */
    like(input: LikeRequest, options?: RpcOptions): UnaryCall<LikeRequest, Empty> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<LikeRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Dislike(KhanAPI.DislikeRequest) returns (google.protobuf.Empty);
     */
    dislike(input: DislikeRequest, options?: RpcOptions): UnaryCall<DislikeRequest, Empty> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DislikeRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddComment(KhanAPI.AddCommentRequest) returns (google.protobuf.Empty);
     */
    addComment(input: AddCommentRequest, options?: RpcOptions): UnaryCall<AddCommentRequest, Empty> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddCommentRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddReply(KhanAPI.AddReplyRequest) returns (google.protobuf.Empty);
     */
    addReply(input: AddReplyRequest, options?: RpcOptions): UnaryCall<AddReplyRequest, Empty> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddReplyRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetComments(KhanAPI.GetCommentsRequest) returns (KhanAPI.GetCommentsResponse);
     */
    getComments(input: GetCommentsRequest, options?: RpcOptions): UnaryCall<GetCommentsRequest, GetCommentsResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCommentsRequest, GetCommentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchCategories(KhanAPI.SearchCategoriesRequest) returns (KhanAPI.SearchCategoriesResponse);
     */
    searchCategories(input: SearchCategoriesRequest, options?: RpcOptions): UnaryCall<SearchCategoriesRequest, SearchCategoriesResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchCategoriesRequest, SearchCategoriesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetReplies(KhanAPI.GetRepliesRequest) returns (KhanAPI.GetRepliesResponse);
     */
    getReplies(input: GetRepliesRequest, options?: RpcOptions): UnaryCall<GetRepliesRequest, GetRepliesResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRepliesRequest, GetRepliesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LikeComment(KhanAPI.LikeCommentRequest) returns (google.protobuf.Empty);
     */
    likeComment(input: LikeCommentRequest, options?: RpcOptions): UnaryCall<LikeCommentRequest, Empty> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<LikeCommentRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCategories(google.protobuf.Empty) returns (KhanAPI.GetCategoriesResponse);
     */
    getCategories(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetCategoriesResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GetCategoriesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchFoodByName(KhanAPI.SearchFoodByNameRequest) returns (KhanAPI.SearchFoodByNameResponse);
     */
    searchFoodByName(input: SearchFoodByNameRequest, options?: RpcOptions): UnaryCall<SearchFoodByNameRequest, SearchFoodByNameResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchFoodByNameRequest, SearchFoodByNameResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchFoodByIngredient(KhanAPI.SearchFoodByIngredientRequest) returns (KhanAPI.SearchFoodByIngredientResponse);
     */
    searchFoodByIngredient(input: SearchFoodByIngredientRequest, options?: RpcOptions): UnaryCall<SearchFoodByIngredientRequest, SearchFoodByIngredientResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchFoodByIngredientRequest, SearchFoodByIngredientResponse>("unary", this._transport, method, opt, input);
    }
}
