// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "search.proto" (package "KhanAPI", syntax proto3)
// tslint:disable
import { Empty } from "./google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message KhanAPI.PostPreviewExplore
 */
export interface PostPreviewExplore {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string shortDescription = 3;
     */
    shortDescription: string;
    /**
     * @generated from protobuf field: string postImage = 4;
     */
    postImage: string;
    /**
     * @generated from protobuf field: string username = 5;
     */
    username: string;
    /**
     * @generated from protobuf field: string profile_pic_url = 6;
     */
    profilePicUrl: string;
}
/**
 * @generated from protobuf message KhanAPI.ProfilePreviewExplore
 */
export interface ProfilePreviewExplore {
    /**
     * @generated from protobuf field: int64 profileID = 1;
     */
    profileID: bigint;
    /**
     * @generated from protobuf field: string username = 2;
     */
    username: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: string profilePicUrl = 4;
     */
    profilePicUrl: string;
    /**
     * @generated from protobuf field: int64 isFollowed = 5;
     */
    isFollowed: bigint;
}
/**
 * @generated from protobuf message KhanAPI.Categories
 */
export interface Categories {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: int32 level = 3;
     */
    level: number;
    /**
     * @generated from protobuf field: optional int32 parent = 4;
     */
    parent?: number;
}
/**
 * @generated from protobuf message KhanAPI.GetAllCategoriesResponse
 */
export interface GetAllCategoriesResponse {
    /**
     * @generated from protobuf field: repeated KhanAPI.Categories categories = 1;
     */
    categories: Categories[];
}
/**
 * @generated from protobuf message KhanAPI.SearchCategoriesRequest
 */
export interface SearchCategoriesRequest {
    /**
     * @generated from protobuf field: repeated int32 categoryID = 1;
     */
    categoryID: number[];
    /**
     * @generated from protobuf field: optional int32 pageNumber = 2;
     */
    pageNumber?: number;
}
/**
 * @generated from protobuf message KhanAPI.SearchCategoriesResponse
 */
export interface SearchCategoriesResponse {
    /**
     * @generated from protobuf field: repeated KhanAPI.PostPreviewExplore posts = 1;
     */
    posts: PostPreviewExplore[];
    /**
     * @generated from protobuf field: int32 pageNumber = 2;
     */
    pageNumber: number;
}
/**
 * @generated from protobuf message KhanAPI.SearchFoodByNameRequest
 */
export interface SearchFoodByNameRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: optional int32 pageNumber = 2;
     */
    pageNumber?: number;
}
/**
 * @generated from protobuf message KhanAPI.SearchFoodByNameResponse
 */
export interface SearchFoodByNameResponse {
    /**
     * @generated from protobuf field: repeated KhanAPI.PostPreviewExplore postPreview = 1;
     */
    postPreview: PostPreviewExplore[];
    /**
     * @generated from protobuf field: int32 pageNumber = 2;
     */
    pageNumber: number;
}
/**
 * @generated from protobuf message KhanAPI.SearchFoodByIngredientRequest
 */
export interface SearchFoodByIngredientRequest {
    /**
     * @generated from protobuf field: repeated string include = 1;
     */
    include: string[];
    /**
     * @generated from protobuf field: repeated string exclude = 2;
     */
    exclude: string[];
    /**
     * @generated from protobuf field: optional int32 pageNumber = 3;
     */
    pageNumber?: number;
}
/**
 * @generated from protobuf message KhanAPI.SearchFoodByIngredientResponse
 */
export interface SearchFoodByIngredientResponse {
    /**
     * @generated from protobuf field: repeated KhanAPI.PostPreviewExplore postPreview = 1;
     */
    postPreview: PostPreviewExplore[];
    /**
     * @generated from protobuf field: int32 pageNumber = 2;
     */
    pageNumber: number;
}
/**
 * @generated from protobuf message KhanAPI.SearchUsernameRequest
 */
export interface SearchUsernameRequest {
    /**
     * @generated from protobuf field: string username = 1;
     */
    username: string;
}
/**
 * @generated from protobuf message KhanAPI.SearchUsernameResponse
 */
export interface SearchUsernameResponse {
    /**
     * @generated from protobuf field: repeated KhanAPI.ProfilePreviewExplore profilePreview = 1;
     */
    profilePreview: ProfilePreviewExplore[];
}
/**
 * @generated from protobuf message KhanAPI.MixedSearchRequest
 */
export interface MixedSearchRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: repeated int32 categoryID = 2;
     */
    categoryID: number[];
    /**
     * @generated from protobuf field: repeated string includeIng = 3;
     */
    includeIng: string[];
    /**
     * @generated from protobuf field: repeated string excludeIng = 4;
     */
    excludeIng: string[];
    /**
     * @generated from protobuf field: optional int32 pageNumber = 5;
     */
    pageNumber?: number;
}
/**
 * @generated from protobuf message KhanAPI.MixedSearchResponse
 */
export interface MixedSearchResponse {
    /**
     * @generated from protobuf field: repeated KhanAPI.PostPreviewExplore posts = 1;
     */
    posts: PostPreviewExplore[];
    /**
     * @generated from protobuf field: int32 pageNumber = 2;
     */
    pageNumber: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class PostPreviewExplore$Type extends MessageType<PostPreviewExplore> {
    constructor() {
        super("KhanAPI.PostPreviewExplore", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "shortDescription", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "postImage", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "profile_pic_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PostPreviewExplore>): PostPreviewExplore {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.title = "";
        message.shortDescription = "";
        message.postImage = "";
        message.username = "";
        message.profilePicUrl = "";
        if (value !== undefined)
            reflectionMergePartial<PostPreviewExplore>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostPreviewExplore): PostPreviewExplore {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string shortDescription */ 3:
                    message.shortDescription = reader.string();
                    break;
                case /* string postImage */ 4:
                    message.postImage = reader.string();
                    break;
                case /* string username */ 5:
                    message.username = reader.string();
                    break;
                case /* string profile_pic_url */ 6:
                    message.profilePicUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostPreviewExplore, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string shortDescription = 3; */
        if (message.shortDescription !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.shortDescription);
        /* string postImage = 4; */
        if (message.postImage !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.postImage);
        /* string username = 5; */
        if (message.username !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.username);
        /* string profile_pic_url = 6; */
        if (message.profilePicUrl !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.profilePicUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.PostPreviewExplore
 */
export const PostPreviewExplore = new PostPreviewExplore$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProfilePreviewExplore$Type extends MessageType<ProfilePreviewExplore> {
    constructor() {
        super("KhanAPI.ProfilePreviewExplore", [
            { no: 1, name: "profileID", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "profilePicUrl", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "isFollowed", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ProfilePreviewExplore>): ProfilePreviewExplore {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.profileID = 0n;
        message.username = "";
        message.name = "";
        message.profilePicUrl = "";
        message.isFollowed = 0n;
        if (value !== undefined)
            reflectionMergePartial<ProfilePreviewExplore>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProfilePreviewExplore): ProfilePreviewExplore {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 profileID */ 1:
                    message.profileID = reader.int64().toBigInt();
                    break;
                case /* string username */ 2:
                    message.username = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string profilePicUrl */ 4:
                    message.profilePicUrl = reader.string();
                    break;
                case /* int64 isFollowed */ 5:
                    message.isFollowed = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProfilePreviewExplore, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 profileID = 1; */
        if (message.profileID !== 0n)
            writer.tag(1, WireType.Varint).int64(message.profileID);
        /* string username = 2; */
        if (message.username !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.username);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string profilePicUrl = 4; */
        if (message.profilePicUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.profilePicUrl);
        /* int64 isFollowed = 5; */
        if (message.isFollowed !== 0n)
            writer.tag(5, WireType.Varint).int64(message.isFollowed);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.ProfilePreviewExplore
 */
export const ProfilePreviewExplore = new ProfilePreviewExplore$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Categories$Type extends MessageType<Categories> {
    constructor() {
        super("KhanAPI.Categories", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "level", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "parent", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Categories>): Categories {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.level = 0;
        if (value !== undefined)
            reflectionMergePartial<Categories>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Categories): Categories {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 level */ 3:
                    message.level = reader.int32();
                    break;
                case /* optional int32 parent */ 4:
                    message.parent = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Categories, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 level = 3; */
        if (message.level !== 0)
            writer.tag(3, WireType.Varint).int32(message.level);
        /* optional int32 parent = 4; */
        if (message.parent !== undefined)
            writer.tag(4, WireType.Varint).int32(message.parent);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.Categories
 */
export const Categories = new Categories$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllCategoriesResponse$Type extends MessageType<GetAllCategoriesResponse> {
    constructor() {
        super("KhanAPI.GetAllCategoriesResponse", [
            { no: 1, name: "categories", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Categories }
        ]);
    }
    create(value?: PartialMessage<GetAllCategoriesResponse>): GetAllCategoriesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.categories = [];
        if (value !== undefined)
            reflectionMergePartial<GetAllCategoriesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllCategoriesResponse): GetAllCategoriesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated KhanAPI.Categories categories */ 1:
                    message.categories.push(Categories.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllCategoriesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated KhanAPI.Categories categories = 1; */
        for (let i = 0; i < message.categories.length; i++)
            Categories.internalBinaryWrite(message.categories[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.GetAllCategoriesResponse
 */
export const GetAllCategoriesResponse = new GetAllCategoriesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchCategoriesRequest$Type extends MessageType<SearchCategoriesRequest> {
    constructor() {
        super("KhanAPI.SearchCategoriesRequest", [
            { no: 1, name: "categoryID", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "pageNumber", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchCategoriesRequest>): SearchCategoriesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.categoryID = [];
        if (value !== undefined)
            reflectionMergePartial<SearchCategoriesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchCategoriesRequest): SearchCategoriesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated int32 categoryID */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.categoryID.push(reader.int32());
                    else
                        message.categoryID.push(reader.int32());
                    break;
                case /* optional int32 pageNumber */ 2:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchCategoriesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated int32 categoryID = 1; */
        if (message.categoryID.length) {
            writer.tag(1, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.categoryID.length; i++)
                writer.int32(message.categoryID[i]);
            writer.join();
        }
        /* optional int32 pageNumber = 2; */
        if (message.pageNumber !== undefined)
            writer.tag(2, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchCategoriesRequest
 */
export const SearchCategoriesRequest = new SearchCategoriesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchCategoriesResponse$Type extends MessageType<SearchCategoriesResponse> {
    constructor() {
        super("KhanAPI.SearchCategoriesResponse", [
            { no: 1, name: "posts", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostPreviewExplore },
            { no: 2, name: "pageNumber", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchCategoriesResponse>): SearchCategoriesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.posts = [];
        message.pageNumber = 0;
        if (value !== undefined)
            reflectionMergePartial<SearchCategoriesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchCategoriesResponse): SearchCategoriesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated KhanAPI.PostPreviewExplore posts */ 1:
                    message.posts.push(PostPreviewExplore.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 pageNumber */ 2:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchCategoriesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated KhanAPI.PostPreviewExplore posts = 1; */
        for (let i = 0; i < message.posts.length; i++)
            PostPreviewExplore.internalBinaryWrite(message.posts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 pageNumber = 2; */
        if (message.pageNumber !== 0)
            writer.tag(2, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchCategoriesResponse
 */
export const SearchCategoriesResponse = new SearchCategoriesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchFoodByNameRequest$Type extends MessageType<SearchFoodByNameRequest> {
    constructor() {
        super("KhanAPI.SearchFoodByNameRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "pageNumber", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchFoodByNameRequest>): SearchFoodByNameRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<SearchFoodByNameRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchFoodByNameRequest): SearchFoodByNameRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* optional int32 pageNumber */ 2:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchFoodByNameRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* optional int32 pageNumber = 2; */
        if (message.pageNumber !== undefined)
            writer.tag(2, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchFoodByNameRequest
 */
export const SearchFoodByNameRequest = new SearchFoodByNameRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchFoodByNameResponse$Type extends MessageType<SearchFoodByNameResponse> {
    constructor() {
        super("KhanAPI.SearchFoodByNameResponse", [
            { no: 1, name: "postPreview", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostPreviewExplore },
            { no: 2, name: "pageNumber", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchFoodByNameResponse>): SearchFoodByNameResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.postPreview = [];
        message.pageNumber = 0;
        if (value !== undefined)
            reflectionMergePartial<SearchFoodByNameResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchFoodByNameResponse): SearchFoodByNameResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated KhanAPI.PostPreviewExplore postPreview */ 1:
                    message.postPreview.push(PostPreviewExplore.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 pageNumber */ 2:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchFoodByNameResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated KhanAPI.PostPreviewExplore postPreview = 1; */
        for (let i = 0; i < message.postPreview.length; i++)
            PostPreviewExplore.internalBinaryWrite(message.postPreview[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 pageNumber = 2; */
        if (message.pageNumber !== 0)
            writer.tag(2, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchFoodByNameResponse
 */
export const SearchFoodByNameResponse = new SearchFoodByNameResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchFoodByIngredientRequest$Type extends MessageType<SearchFoodByIngredientRequest> {
    constructor() {
        super("KhanAPI.SearchFoodByIngredientRequest", [
            { no: 1, name: "include", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "exclude", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "pageNumber", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchFoodByIngredientRequest>): SearchFoodByIngredientRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.include = [];
        message.exclude = [];
        if (value !== undefined)
            reflectionMergePartial<SearchFoodByIngredientRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchFoodByIngredientRequest): SearchFoodByIngredientRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string include */ 1:
                    message.include.push(reader.string());
                    break;
                case /* repeated string exclude */ 2:
                    message.exclude.push(reader.string());
                    break;
                case /* optional int32 pageNumber */ 3:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchFoodByIngredientRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string include = 1; */
        for (let i = 0; i < message.include.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.include[i]);
        /* repeated string exclude = 2; */
        for (let i = 0; i < message.exclude.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.exclude[i]);
        /* optional int32 pageNumber = 3; */
        if (message.pageNumber !== undefined)
            writer.tag(3, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchFoodByIngredientRequest
 */
export const SearchFoodByIngredientRequest = new SearchFoodByIngredientRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchFoodByIngredientResponse$Type extends MessageType<SearchFoodByIngredientResponse> {
    constructor() {
        super("KhanAPI.SearchFoodByIngredientResponse", [
            { no: 1, name: "postPreview", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostPreviewExplore },
            { no: 2, name: "pageNumber", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchFoodByIngredientResponse>): SearchFoodByIngredientResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.postPreview = [];
        message.pageNumber = 0;
        if (value !== undefined)
            reflectionMergePartial<SearchFoodByIngredientResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchFoodByIngredientResponse): SearchFoodByIngredientResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated KhanAPI.PostPreviewExplore postPreview */ 1:
                    message.postPreview.push(PostPreviewExplore.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 pageNumber */ 2:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchFoodByIngredientResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated KhanAPI.PostPreviewExplore postPreview = 1; */
        for (let i = 0; i < message.postPreview.length; i++)
            PostPreviewExplore.internalBinaryWrite(message.postPreview[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 pageNumber = 2; */
        if (message.pageNumber !== 0)
            writer.tag(2, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchFoodByIngredientResponse
 */
export const SearchFoodByIngredientResponse = new SearchFoodByIngredientResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchUsernameRequest$Type extends MessageType<SearchUsernameRequest> {
    constructor() {
        super("KhanAPI.SearchUsernameRequest", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SearchUsernameRequest>): SearchUsernameRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.username = "";
        if (value !== undefined)
            reflectionMergePartial<SearchUsernameRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchUsernameRequest): SearchUsernameRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string username */ 1:
                    message.username = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchUsernameRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string username = 1; */
        if (message.username !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.username);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchUsernameRequest
 */
export const SearchUsernameRequest = new SearchUsernameRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchUsernameResponse$Type extends MessageType<SearchUsernameResponse> {
    constructor() {
        super("KhanAPI.SearchUsernameResponse", [
            { no: 1, name: "profilePreview", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ProfilePreviewExplore }
        ]);
    }
    create(value?: PartialMessage<SearchUsernameResponse>): SearchUsernameResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.profilePreview = [];
        if (value !== undefined)
            reflectionMergePartial<SearchUsernameResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchUsernameResponse): SearchUsernameResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated KhanAPI.ProfilePreviewExplore profilePreview */ 1:
                    message.profilePreview.push(ProfilePreviewExplore.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchUsernameResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated KhanAPI.ProfilePreviewExplore profilePreview = 1; */
        for (let i = 0; i < message.profilePreview.length; i++)
            ProfilePreviewExplore.internalBinaryWrite(message.profilePreview[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.SearchUsernameResponse
 */
export const SearchUsernameResponse = new SearchUsernameResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MixedSearchRequest$Type extends MessageType<MixedSearchRequest> {
    constructor() {
        super("KhanAPI.MixedSearchRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "categoryID", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "includeIng", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "excludeIng", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "pageNumber", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<MixedSearchRequest>): MixedSearchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.categoryID = [];
        message.includeIng = [];
        message.excludeIng = [];
        if (value !== undefined)
            reflectionMergePartial<MixedSearchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MixedSearchRequest): MixedSearchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* repeated int32 categoryID */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.categoryID.push(reader.int32());
                    else
                        message.categoryID.push(reader.int32());
                    break;
                case /* repeated string includeIng */ 3:
                    message.includeIng.push(reader.string());
                    break;
                case /* repeated string excludeIng */ 4:
                    message.excludeIng.push(reader.string());
                    break;
                case /* optional int32 pageNumber */ 5:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MixedSearchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* repeated int32 categoryID = 2; */
        if (message.categoryID.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.categoryID.length; i++)
                writer.int32(message.categoryID[i]);
            writer.join();
        }
        /* repeated string includeIng = 3; */
        for (let i = 0; i < message.includeIng.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.includeIng[i]);
        /* repeated string excludeIng = 4; */
        for (let i = 0; i < message.excludeIng.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.excludeIng[i]);
        /* optional int32 pageNumber = 5; */
        if (message.pageNumber !== undefined)
            writer.tag(5, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.MixedSearchRequest
 */
export const MixedSearchRequest = new MixedSearchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MixedSearchResponse$Type extends MessageType<MixedSearchResponse> {
    constructor() {
        super("KhanAPI.MixedSearchResponse", [
            { no: 1, name: "posts", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostPreviewExplore },
            { no: 2, name: "pageNumber", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<MixedSearchResponse>): MixedSearchResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.posts = [];
        message.pageNumber = 0;
        if (value !== undefined)
            reflectionMergePartial<MixedSearchResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MixedSearchResponse): MixedSearchResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated KhanAPI.PostPreviewExplore posts */ 1:
                    message.posts.push(PostPreviewExplore.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 pageNumber */ 2:
                    message.pageNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MixedSearchResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated KhanAPI.PostPreviewExplore posts = 1; */
        for (let i = 0; i < message.posts.length; i++)
            PostPreviewExplore.internalBinaryWrite(message.posts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 pageNumber = 2; */
        if (message.pageNumber !== 0)
            writer.tag(2, WireType.Varint).int32(message.pageNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KhanAPI.MixedSearchResponse
 */
export const MixedSearchResponse = new MixedSearchResponse$Type();
/**
 * @generated ServiceType for protobuf service KhanAPI.SearchAPI
 */
export const SearchAPI = new ServiceType("KhanAPI.SearchAPI", [
    { name: "GetAllCategories", options: {}, I: Empty, O: GetAllCategoriesResponse },
    { name: "SearchFoodByName", options: {}, I: SearchFoodByNameRequest, O: SearchFoodByNameResponse },
    { name: "SearchFoodByIngredient", options: {}, I: SearchFoodByIngredientRequest, O: SearchFoodByIngredientResponse },
    { name: "SearchCategories", options: {}, I: SearchCategoriesRequest, O: SearchCategoriesResponse },
    { name: "SearchUsername", options: {}, I: SearchUsernameRequest, O: SearchUsernameResponse },
    { name: "MixedSearch", options: {}, I: MixedSearchRequest, O: MixedSearchResponse }
]);
