syntax = "proto3";

import "google/protobuf/empty.proto";

package KhanAPI;
option go_package = "./../../pkg/PostAPIService";

service PostAPI {
  rpc GetProfilePosts (GetProfilePostsRequests) returns (GetProfilePostsResponse);
  rpc GetPost (GetPostRequest) returns (GetPostResponse);
  rpc SetPost (SetPostRequest) returns (google.protobuf.Empty);
  rpc SuggestIngredient (SuggestIngredientRequest) returns (SuggestIngredientResponse);
  rpc AddImageForPost (AddImageForPostRequest) returns (google.protobuf.Empty);
}

message Post {
  int64 id = 1;
  string title = 2;
  map<string, string> ingredients = 3;
  string description = 4;
  int32 numImages = 5;
  repeated string imageUrls = 6;
  string username = 7;
  string profilePicUrl = 8;
}

message PostPreview {
  int64 id = 1;
  string title = 2;
  string ShortDescription = 3;
  string image = 4;
}

message SetPostRequest {
  string title = 1;
  map<string, string> ingredients = 2;
  string description = 3;
  int32 numImages = 4;
}

message GetProfilePostsRequests {
  int64 profileID = 1;
}

message GetProfilePostsResponse {
  repeated PostPreview postPreview = 1;
}

message GetPostRequest {
  int64 postID = 1;
}

message GetPostResponse {
  Post post = 1;
}

message SuggestIngredientRequest {
  string name = 1;
}

message SuggestIngredientResponse {
  repeated string ingredients = 1;
}

message AddImageForPostRequest {
  string PostImageToken = 1;
}