syntax = "proto3";

import "google/protobuf/empty.proto";

package KhanAPI;
option go_package = "./../../pkg/PostAPIService";

service PostAPI {
  rpc GetProfilePosts (GetProfilePostsRequests) returns (GetProfilePostsResponse);
  rpc GetPost (GetPostRequest) returns (GetPostResponse);
  rpc SetPost (SetPostRequest) returns (SetPostResponse);
  rpc GetCategories (google.protobuf.Empty) returns (GetCategoriesResponse);
  rpc SuggestIngredient (SuggestIngredientRequest) returns (SuggestIngredientResponse);
  rpc AddImageForPost (AddImageForPostRequest) returns (google.protobuf.Empty);
  rpc Like (LikeRequest) returns (google.protobuf.Empty);
  rpc Dislike (DislikeRequest) returns (google.protobuf.Empty);
  rpc AddComment (AddCommentRequest) returns (Comment);
  rpc AddReply (AddReplyRequest) returns (Comment);
  rpc GetComments (GetCommentsRequest) returns (GetCommentsResponse);
  rpc GetReplies (GetRepliesRequest) returns (GetRepliesResponse);
  rpc LikeComment (LikeCommentRequest) returns (google.protobuf.Empty);
  rpc DislikeComment (DislikeCommentRequest) returns (google.protobuf.Empty);
  rpc ReportComment (RepostCommentRequest) returns (google.protobuf.Empty);
  rpc DeleteComment (DeleteCommentRequest) returns (google.protobuf.Empty); 
  rpc PinPost (PinPostRequest) returns (google.protobuf.Empty);
  rpc UnpinPost (UnpinPostRequest) returns (google.protobuf.Empty);
  rpc GetPins (GetPinsRequest) returns (GetPinsResponse);
  rpc DeletePost (DeletePostRequest) returns (google.protobuf.Empty);
  rpc LoadTimeLine (LoadTimeLineRequest) returns (LoadTimeLineResponse);
}

message Post {
  int64 id = 1;
  string title = 2;
  map<string, string> ingredients = 3;
  string description = 4;
  int32 numImages = 5;
  int32 numLikes = 6;
  int32 numComments = 7;
  bool like = 8;
  repeated string imageUrls = 9;
  string username = 10;
  string profilePicUrl = 11;
  string category = 12;
  optional bool pinned = 13;
  int32 view = 14;
}

message PostPreview {
  int64 id = 1;
  string title = 2;
  string ShortDescription = 3;
  string image = 4;
  int32 numLikes = 6;
  int32 numComments = 7;
  bool isLiked = 8;
}


message SetPostRequest {
  string title = 1;
  map<string, string> ingredients = 2;
  string description = 3;
  int32 categoryID = 4;
  int32 numImages = 5;
}

message SetPostResponse {
  int64 id = 1;
}

message GetProfilePostsRequests {
  int64 profileID = 1;
  optional int32 pageNumber = 2;
}

message GetProfilePostsResponse {
  repeated PostPreview postPreview = 1;
  int32 pageNumber = 2;
}

message GetPostRequest {
  int64 postID = 1;
}

message GetPostResponse {
  Post post = 1;
}

message SuggestIngredientRequest {
  string name = 1;
}

message SuggestIngredientResponse {
  repeated string ingredients = 1;
}

message AddImageForPostRequest {
  string PostImageToken = 1;
}

message LikeRequest {
  int64 post_id = 1;
}

message DislikeRequest {
  int64 post_id = 1;
}


message AddCommentRequest {
  string comment = 1;
  int64 postID = 2;
}

message AddReplyRequest {
  string comment = 1;
  int64 commentID = 2;
}

message GetCommentsRequest {
  int64 postID = 1;
}

message GetCommentsResponse {
  repeated Comment comments = 1;
}

message Comment {
  int64 ID = 1;
  string name = 2;
  string username = 3;
  string profileUrl = 4;
  string comment = 5;
  string time = 6;
  bool hasReplies = 7;
  bool isLiked = 8;
  int32 numLikes = 9;
  bool owned = 10;
  optional int64 parentId = 11;
}

message GetRepliesRequest {
  int64 commentID = 1;
}

message GetRepliesResponse {
  repeated Comment comments = 1;
}

message LikeCommentRequest {
  int64 commentID = 1;
}

message DislikeCommentRequest {
  int64 commentID = 1;
}

message RepostCommentRequest {
  int64 id = 1;
}

message Category {
  int32 id = 1;
  string name = 2;
  int32 level = 3;
  optional int32 parent =4;
}

message GetCategoriesResponse {
  repeated Category categories = 1;
}

message PinPostRequest {
  int64 id = 1;
}

message UnpinPostRequest {
  int64 id = 1;
}

message PinedPost {
  int64 id = 1;
  string title = 2;
  string image_url = 3;
}

message GetPinsRequest {
  int64 profileID = 1;
}

message GetPinsResponse {
  repeated PinedPost PinedPost = 1;
}

message DeletePostRequest {
  int64 id = 1;
}
message DeleteCommentRequest {
  int64 id = 1;
}

message LoadTimeLineRequest {
  int32 pageNumber = 1;
}

message LoadTimeLineResponse {
  message TimeLinePost {
    int64 id = 1;
    string title = 2;
    string ShortDescription = 3;
    string image = 4;
    int32 numLikes = 6;
    int32 numComments = 7;
    bool isLiked = 8;
    string username = 9;
    string profilePicUrl = 10;
  }
  repeated TimeLinePost posts = 1;
  int32 pageNumber = 2;
}