syntax = "proto3";

import "google/protobuf/empty.proto";

package KhanAPI;
option go_package = "./../../pkg/PostAPIService";

service PostAPI {
  rpc GetProfilePosts (GetProfilePostsRequests) returns (GetProfilePostsResponse);
  rpc GetPost (GetPostRequest) returns (GetPostResponse);
  rpc SetPost (SetPostRequest) returns (google.protobuf.Empty);
  rpc SuggestIngredient (SuggestIngredientRequest) returns (SuggestIngredientResponse);
}

message Post {
  string title = 1;
  map<string, string> ingredients = 2;
  string description = 3;
  int32 numImages = 4; 
}

message SetPostRequest {
  Post post = 1;
}

message GetProfilePostsRequests {
  int64 profileID = 1;
}

message GetProfilePostsResponse {
  repeated Post post = 1;
}

message GetPostRequest {
  int64 postID = 1;
}

message GetPostResponse {
  Post post = 1;
}

message SuggestIngredientRequest {
  string name = 1;
}

message SuggestIngredientResponse {
  repeated string ingerdients = 1;
}