syntax = "proto3";

import "google/protobuf/empty.proto";


package KhanAPI;
option go_package = "./../../pkg/UserAPIService";

service UserAPI {
  rpc RefreshToken (google.protobuf.Empty) returns (RefreshTokenResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc ForgetPassword (ForgetPasswordRequest) returns (google.protobuf.Empty);
  rpc NewPasswordWithToken (NewPasswordWithTokenRequest) returns (google.protobuf.Empty);
  rpc SignUp (SignUpRequest) returns (SignUpResponse);
  rpc CodeVerification (CodeVerificationRequest) returns (CodeVerificationResponse);
  rpc PersonalInfoCompletion (PersonalInfoCompletionRequest) returns (google.protobuf.Empty);
  rpc EditProfileInfo (EditProfileInfoRequest) returns (google.protobuf.Empty);
  rpc GetUserInfo (google.protobuf.Empty) returns (GetUserInfoResponse);
  rpc ChangeUsername (ChangeUsernameRequest) returns (google.protobuf.Empty);
  rpc ChangeEmail (ChangeEmailRequest) returns (ChangeEmailResponse);
  rpc ConfirmChangeEmail (ConfirmChangeEmailRequest) returns (google.protobuf.Empty);
  rpc ChangePassword (ChangePasswordRequest) returns (google.protobuf.Empty);
  rpc ChangeProfilePic (ChangeProfilePicRequest) returns (google.protobuf.Empty);
  rpc GetProfile (GetProfileRequests) returns (GetProfileResponse);
  rpc GetCities (GetCitiesRequest) returns (GetCitiesResponse);
  rpc DeleteAccount (DeleteAccountRequest) returns (google.protobuf.Empty);
  rpc SearchUsername (SearchUsernameRequest) returns (SearchUsernameResponse);
  rpc Follow (FollowRequest) returns (google.protobuf.Empty);
  rpc Unfollow (UnfollowRequest) returns (google.protobuf.Empty);
  rpc GetFollowingList (GetFollowingListRequest) returns (GetFollowingListResponse);
  rpc GetFollowerList (GetFollowerListRequest) returns (GetFollowerListResponse);
}

message User {
  string fName = 1;
  string lName = 2;
  string username = 3;
  string email = 4;
  string birthDay = 5;
  string gender = 6;
  string profilePicUrl = 7;
  string city = 8;
  string bio = 9;
}

message Profile {
  int64 id = 1;
  string name = 2;
  string username = 3;
  string pronouns = 5;
  string bio = 6;
  string city = 7;
  string profilePicUrl = 8;
  int64 followerCnt = 9;
  int64 followingCnt = 10;
  bool isFollowed = 11;
}

message RefreshTokenResponse {
  string Token = 1;
}


// login begin

message LoginRequest {
  string userNameOrEmail = 1;
  string password = 2;
}

message LoginResponse {
  string jwtToken = 1;
  string refreshToken = 2;
}

// login end

// forget pass begin

message ForgetPasswordRequest {
  string userNameOrEmail = 1;
}

message NewPasswordWithTokenRequest {
  string resetPasswordToken = 1;
  string password = 2;
}

// forget pass end

// signUp begin

message SignUpRequest {
  string email = 1;
  string username = 2;
  string password = 3;
}

message SignUpResponse {
  string token = 1;
}

message CodeVerificationRequest {
  string signUpToken = 1;
  string code = 2;
}

message CodeVerificationResponse {
  string jwtToken = 1;
  string refreshToken = 2;
}

// token in header
message PersonalInfoCompletionRequest {
  string fName = 1;
  string lName = 2;
  string birthDay = 3;
  string gender = 4;
  string bio = 5;
}

// signUp end

// EditProfile begin

message GetUserInfoResponse {
    User user = 1;
}

message EditProfileInfoRequest {
  optional string fName = 1;
  optional string lName = 2;
  optional string gender = 3;
  optional string birthDay = 4;
  optional int32  cityID = 5;
  optional string bio = 6;
}


message ChangeUsernameRequest {
  string newUsername = 1;
}

message ChangeEmailRequest {
  string newEmail = 1;
}

message ChangeEmailResponse {
  string changeEmailToken = 1;
}

message ConfirmChangeEmailRequest {
  string changeEmailToken = 1;
  string code = 2;
}

message ChangePasswordRequest {
  string oldPassword = 1;
  string newPassword = 2;
}

message ChangeProfilePicRequest {
  string profilePicToken = 1;
}

// EditProfile End

message GetProfileRequests {
  optional string username = 1;
}

message GetProfileResponse {
  Profile profile = 1;
}

message GetCitiesRequest {
  string cityPattern = 1;
}

message City {
  int32 id = 1;
  string name = 2;
}

message GetCitiesResponse {
  repeated City cities = 1;
}

message DeleteAccountRequest {
  string password = 1;
}

message SearchUsernameRequest {
  string username = 1;
}

message SearchUsernameResponse {
  repeated ProfilePreview ProfilePreview = 1;
}

message ProfilePreview {
  int64 profileID = 1;
  string username = 2;
  string name = 3;
  string profilePicUrl = 4;
}

message FollowRequest {
  int64 profileID = 1;
}

message UnfollowRequest {
  int64 profileID = 1;
}

message GetFollowingListRequest {
  int64 profileID = 1;
}

message GetFollowingListResponse {
  repeated ProfilePreview profilePreview = 1;
}

message GetFollowerListRequest {
  int64 profileID = 1;
}

message GetFollowerListResponse {
  repeated ProfilePreview profilePreview = 1;
}